version: '3.9'

services: 





    splash:
        image: scrapinghub/splash:3.5.0
        ports:
            - "8050:8050"
        
        container_name: splash

        command: --disable-private-mode

        volumes:
            - ./data/filters:/etc/splash/filters
            - ./data/js-profiles:/etc/splash/js-profiles
            - ./data/lua_modules:/etc/splash/lua_modules
            - ./data/proxy-profiles:/etc/splash/proxy-profiles
        restart: unless-stopped

        depends_on: 
            - db


    web:
        build: 
            context: .

        env_file: .env

        volumes: 
            - .:/code

        environment: 
            - DJANGO_SUPERUSER_EMAIL=admin@mail.com
            - DJANGO_SUPERUSER_USERNAME=admin
            - DJANGO_SUPERUSER_PASSWORD=admin

        command: gunicorn booking_hotel_scraper.wsgi:application --bind 0.0.0.0:8000
        
        depends_on: 
            - db
            - splash
            
        ports:
            - "8000:8000"

        links:
            - db:db



    db:
        image: postgres

        #volumes:
        #    - postgres_data:/var/lib/postgresql/data/

        #environment:
        #  - POSTGRES_USER=hug58
        #  - POSTGRES_PASSWORD=123456
        #  - POSTGRES_DB=bookingDB

        env_file: .env



#volumes:
#  postgres_data: