# Generated by Django 3.2 on 2021-04-27 20:23

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_page', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('direction', models.CharField(max_length=255)),
                ('score_review', models.CharField(max_length=255)),
                ('score', models.CharField(max_length=255)),
                ('photos', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=5)),
            ],
            options={
                'db_table': 'scraper_hotel',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('room_code', models.CharField(max_length=15, unique=True)),
                ('size', models.CharField(blank=True, max_length=15, null=True)),
                ('photos', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=5)),
                ('facilities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='hotel.hotel')),
            ],
            options={
                'db_table': 'scraper_room',
            },
        ),
    ]
